### PR TITLE
Fixes and improvements

### PR DESCRIPTION
**Pull request by Anywhere-Music-Player**
Some fixes for iPhone 6, bug for deleting resources and also added nice thumbnail view for png files, so it's easily to edit levels now.

### CODE REVIEW

**Comment by oxeron** [comment]
Thanks for the PR, but you should have divided it into 3 different PR so merge and revert is more easy
Can you do this ?

**Comment by Anywhere-Music-Player** [comment]
I don't know how. I just created pr on github site and it added these changes.

**Comment by oxeron** [comment]
I think you must do one branch for each feature, and pull a PR from each of these branch. This is what I did when pulling requests to cocos2d

**Comment by Anywhere-Music-Player** [comment]
Ohh my.. for every commit a new branch.. Maybe there is another way.. and it's not a big changes here, can be a single commit.

**Comment by oxeron** [comment]
not every commit, every feature

**Comment by Anywhere-Music-Player** [comment]
There is a small fixes and 1 new feature, I think it's ok for now ^^ so it's one branch feature.

**Comment by oxeron** [comment]
Yahoo ! you committed all your changes in the same Pull Request :( .... It's difficult to merge everything now, especially, I saw you removed some actions on mouse hover

Now, I can't accept dome changed and discuss others, that's why we do one branch per feature, so when you make your pull request, it's easier to maintain ...

I'll have to read everything you did to see what's good to keep, but thanks for the effort

**Comment by Anywhere-Music-Player** [comment]
Ohh, sorry, I already forgot about all this. Thats strange to me that it's pushing all my changes to this pull.. well git is very new to me :) 

However, all I've done is needed %100. I'm doing these changes for my game I'm currently actively developing and for generally to improve CocosBuilder. 
Should l close this request? Because every time I will not be creating a new branch for any commit ^^ so you can decide to accept all these changes or ignore them\

**Comment by oxeron** [comment]
That's the problem when multiple people work on a single project, I did not make the rules, trust me it annoyed me too at first :)

For exemple what was the purpose of these lines ?

```
+    for (int i=0; i< customProps.count; i++) {
+        CustomPropSetting *setting = [customProps objectAtIndex:i];
+    //for (CustomPropSetting *setting in customProps)
+    //{
```

**Comment by Anywhere-Music-Player** [comment]
The comment to this commit as says: Added sorting for custom properties. So, that for it. But yea - I'm sorting that array and it's can't be fast enumerated, because there will be exception: been modified while enumerated..

**Comment by oxeron** [comment]
OK, get it, thanks, i'll merge all this

**Comment by oxeron** [comment]
If you intend to work on some big changes, please make a new branch and make a pull request from there, it's easier to maintain on a long distance

**Comment by Anywhere-Music-Player** [comment]
Yea, but this project isn't supported officially, cocos2d not supported. I'm doing all this just for myself. Bumped you with this pull, just to see if u still active with it. Anyway, this project has no future, so sad..

**Pull request merged**
